blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import main_page, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(main_page), name='blog_main'),
    path('detail/<int:pk>', cache_page(60)(ArticleDetailView.as_view()), name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('sender/', include('email_sender.urls', namespace='sender')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
]

email_sender/urls.py
from django.urls import path
from email_sender.views import ClientCreateView, ClientDeleteView, ClientDetailView, ClientListView, ClientUpdateView, \
    MailingCreateView, MailingDetailView, MailingListView, MailingUpdateView, MessageCreateView, MessageDeleteView, \
    MessageDetailView, MessageListView, MessageUpdateView, MailingDeleteView, AttemptListView
from email_sender.apps import EmailSenderConfig


app_name = EmailSenderConfig.name

urlpatterns = [
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),

    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_detail/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),

    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_detail/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),

    path('attempt_list/', AttemptListView.as_view(), name='attempt_list'),
]

email_sender/models.py
from django.db import models

from users.models import User


# Create your models here.
class Client(models.Model):
    '''
    Клиенты - это те, кто получает рассылки, а не те, кто создает!!!!
    '''
    email = models.CharField(max_length=150, verbose_name='контактный email')
    name = models.CharField(max_length=150, verbose_name='Ф.И.О.')
    comment = models.TextField(verbose_name='комментарий', blank=True, null=True)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True,
                             verbose_name='Пользователь-Владелец')

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self) -> str:
        return f'{self.name} - {self.email}'


class Message(models.Model):
    topic_mail = models.CharField(max_length=150, verbose_name='Тема письма')
    bode_mail = models.TextField(verbose_name='Тело письма')

    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True,
                             verbose_name='Пользователь-Владелец')

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
    
    def __str__(self) -> str:
        return f'{self.topic_mail}'


class Mailing(models.Model):
    '''
    Настройка рассылки
    '''
    PERIOD_MAILING = [
        ('day', 'Раз в день'),
        ('week', 'Раз в неделю'),
        ('month', 'Раз в месяц'),
    ]

    STATUS_MAILING = [
        ('create', 'Создана'),
        ('start', 'Запущена'),
        ('stop', 'Завершена'),
    ]

    date_start = models.DateTimeField(verbose_name='дата начала рассылки (первая рассылка)')
    periodic = models.CharField(verbose_name='Периодичность рассылки', choices=PERIOD_MAILING, default='day')
    status = models.CharField(verbose_name='Статус рассылки', choices=STATUS_MAILING, default='create')
    date_end = models.DateTimeField(verbose_name='Дата окончания расылки', null=True, blank=True)

    client = models.ManyToManyField(Client, verbose_name='Клиенты для которых рассылка')

    message = models.OneToOneField(Message, on_delete=models.CASCADE, verbose_name='Сообщение для рассылки')

    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Пользователь-Владелец')

    class Meta:
        verbose_name = 'Настройка рассылки'
        verbose_name_plural = 'Настройки рассылки'
        permissions = [
            ('can_off_mailing', 'can off mailing'),
            ('cant_edit_mailing', 'can edit mailing'),
            ('cant_change_list_mailing', 'cant change list mailing'),
            ('cant_edit_mailing_message', 'cant edit mailing message'),
            ('can_view_mailing', 'can view mailing'),
            ('can_view_user_list', 'can view user list'),
        ]

    def __str__(self) -> str:
        return f'{self.pk}'


class Attempt(models.Model):
    STATUS_ATTEMPT = [
        ('pos', 'Успешно'),
        ('neg', 'Не успешно'),
    ]

    last_date = models.DateTimeField(verbose_name='Дата и время последней попытки рассылки')
    status = models.CharField(max_length=150, verbose_name='статус рассылки')
    answer = models.CharField(verbose_name='Ответ почтового сервера', blank=True, null=True)

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='попытка рассылки',
                                blank=True, null=True)

    class Meta:
        verbose_name = 'Попытки рассылки'
        verbose_name_plural = 'Попытки расылки'

    def __str__(self) -> str:
        return f'{self.last_date} - {self.status}'

email_sender/forms.py
from django.forms import ModelForm

from email_sender.models import Client, Mailing, Message, Attempt


class ClientFormCreate(ModelForm):
    class Meta:
        model = Client
        exclude = ('user',)


class ClientFormUpdate(ModelForm):
    class Meta:
        model = Client
        exclude = ('user',)


class MessageFormCreate(ModelForm):
    class Meta:
        model = Message
        exclude = ('user',)


class MessageFormUpdate(ModelForm):
    class Meta:
        model = Message
        exclude = ('user',)


class MailingFormCreate(ModelForm):
    class Meta:
        model = Mailing
        exclude = ('user',)


class MailingFormUpdate(ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'


class AttemptForm(ModelForm):
    class Meta:
        model = Attempt
        fields ='__all__'


class ManagerMailingDetailForm(ModelForm):
    class Meta:
        model = Mailing
        fields = ('status',)

email_sender/views.py
from lib2to3.fixes.fix_input import context
from urllib import request

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.forms import BaseModelForm, inlineformset_factory
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from email_sender.cron import send_func
from email_sender.forms import ClientFormCreate, ClientFormUpdate, MailingFormCreate, MailingFormUpdate, \
    MessageFormCreate, MessageFormUpdate, AttemptForm, ManagerMailingDetailForm
from email_sender.models import Client, Mailing, Message, Attempt
from email_sender.services import send_send


# Create your views here.

class ClientCreateView(CreateView):
    model = Client
    form_class = ClientFormCreate
    success_url = reverse_lazy('sender:client_list')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        client = form.save()
        user = self.request.user
        client.user = user
        client.save()
        return super().form_valid(form)
    

class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientFormUpdate
    
    def get_success_url(self):
        return reverse_lazy('sender:client_detail', kwargs={'pk': self.object.pk})

class ClientListView(ListView):
    model = Client


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('sender:client_list')


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageFormCreate
    success_url = reverse_lazy('sender:message_list')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        message = form.save()
        user = self.request.user
        message.user = user
        message.save()
        return super().form_valid(form)

class MessageListView(ListView):
    model = Message


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageFormUpdate
    
    def get_success_url(self):
        return reverse_lazy('sender:message_detail', kwargs={'pk': self.object.pk})


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('sender:message_list')


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingFormCreate
    success_url = reverse_lazy('sender:mailing_list')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        mailing = form.save()
        user = self.request.user
        mailing.user = user
        mailing.save()
        send_func('go_mail', mailing_pk=mailing.pk, message_pk=mailing.message.pk)
        return super().form_valid(form)


class MailingListView(ListView):
    model = Mailing


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MailingFormset = inlineformset_factory(Mailing, Attempt, AttemptForm, extra=0)
        if self.request.method == 'POST':
            context_data['formset'] = MailingFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MailingFormset(instance=self.object)
        return context_data


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingFormUpdate

    
    def get_success_url(self):
        return reverse_lazy('sender:mailing_detail', kwargs={'pk': self.object.pk})


    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return MailingFormUpdate
        if user.has_perm('email_sender.cant_edit_mailing'):
            return ManagerMailingDetailForm



class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('sender:mailing_list')

class AttemptListView(ListView):
    model = Attempt

email_sender/templates/email_sender/attempt_list.html
{% extends '../base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">


      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for attempt in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">Дата попытки расслыки: {{attempt.last_date}}</p>
              <p class="card-text">Рассылка: {{attempt.mailing}}</p>
              <p class="card-text">Статус рассылки: {{attempt.status}}</p>
              <p class="card-text">Ответ сервера: {{attempt.answer}}</p>
              <div class="d-flex justify-content-between align-items-center">
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

email_sender/templates/email_sender/client_confirm_delete.html
{% extends '../base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <p>Действительно хотите удалить {{object.email}} - {{object.name}}???</p>
                    <button type="submit" class="btn btn-danger">
                        Удалить
                    </button>
                    <br>
                    <a class="btn btn-primary" href="{% url 'sender:client_detail' object.pk %}" role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

email_sender/templates/email_sender/client_detail.html
{% extends '../base.html' %}
{% block content %}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">email: {{object.email}}</p>
              <p class="card-text">ФИО: {{object.name}}</p>
              <p class="card-text">Комментарий: {{object.comment}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if object.user == user %}
                    <a class="btn btn-primary" href="{% url 'sender:client_update' client.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-danger" href="{% url 'sender:client_delete' client.pk %}" role="button">Удалить</a>
                  {% endif %}
                    <a class="btn btn-primary" href="{% url 'sender:client_list' %}" role="button">Весь Список</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

email_sender/templates/email_sender/client_form.html
{% extends '../base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-7">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
                <br>
            </div>
        </div>
    </form>
</div>
{% endblock %}

email_sender/templates/email_sender/client_list.html
{% extends '../base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row">
            {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'sender:client_create' %}" role="button">Добаивть Клиента</a>
            {% endif %}
        </div>

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for client in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{client.email}}</p>
              <p class="card-text">{{client.name}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'sender:client_detail' client.pk %}" role="button">Подробно</a>
                </div>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

email_sender/templates/email_sender/mailing_confirm_delete.html
{% extends '../base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <p>Действительно хотите удалить рассылку ???</p>
                    <button type="submit" class="btn btn-danger">
                        Удалить
                    </button>
                    <br>
                    <a class="btn btn-primary" href="{% url 'sender:mailing_detail' object.pk %}" role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

email_sender/templates/email_sender/mailing_detail.html
{% extends '../base.html' %}
{% block content %}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">Дата начала: {{object.date_start}}</p>
              <p class="card-text">Периодичность: {{object.periodic}}</p>
              <p class="card-text">Статус: {{object.status}}</p>
              <p class="card-text">Дата окончания: {{object.date_end}}</p>
              <p class="card-text">Ответ: {{object.attempt}}</p>
              <p class="card-text">Сообщение: {{object.message}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-primary" href="{% url 'sender:mailing_update' mailing.pk %}" role="button">Редактировать</a>
                  <a class="btn btn-danger" href="{% url 'sender:mailing_delete' mailing.pk %}" role="button">Удалить</a>
                    <a class="btn btn-primary" href="{% url 'sender:mailing_list' %}" role="button">Весь Список</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-5">
            <div class="card">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

email_sender/templates/email_sender/mailing_form.html
{% extends '../base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-7">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
                <br>
            </div>
        </div>
    </form>
</div>
{% endblock %}

email_sender/templates/email_sender/mailing_list.html
{% extends '../base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row">
            {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'sender:mailing_create' %}" role="button">Добаивть Рассылку</a>
            {% endif %}
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for mailing in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{mailing.message}}</p>
                        <p class="card-text">{{mailing.date_start}}</p>
                        <p class="card-text">{{mailing.date_end}}</p>
                        <p class="card-text">{{mailing.periodic}}</p>
                        <p class="card-text">{{mailing.status}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if perms.email_sender.can_view_mailing or user == mailing.user %}
                                <a class="btn btn-primary" href="{% url 'sender:mailing_detail' mailing.pk %}"
                                   role="button">Подробно</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

email_sender/templates/email_sender/message_confirm_delete.html
{% extends '../base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <p>Действительно хотите удалить сообщение с темой {{object.topic_mail}}???</p>
                    <button type="submit" class="btn btn-danger">
                        Удалить
                    </button>
                    <br>
                    <a class="btn btn-primary" href="{% url 'sender:message_detail' object.pk %}" role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

email_sender/templates/email_sender/message_detail.html
{% extends '../base.html' %}
{% block content %}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">Тема письма: {{object.topic_mail}}</p>
              <p class="card-text">Текст письма: {{object.bode_mail}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if object.user == user %}
                    <a class="btn btn-primary" href="{% url 'sender:message_update' message.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-danger" href="{% url 'sender:message_delete' message.pk %}" role="button">Удалить</a>
                  {% endif %}
                    <a class="btn btn-primary" href="{% url 'sender:message_list' %}" role="button">Весь Список</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

email_sender/templates/email_sender/message_form.html
{% extends '../base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-7">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
                <br>
            </div>
        </div>
    </form>
</div>
{% endblock %}

email_sender/templates/email_sender/message_list.html
{% extends '../base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row">
            {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'sender:message_create' %}" role="button">Добаивть Сообщение</a>
            {% endif %}
        </div>

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for message in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{message.topic_mail}}</p>
              <p class="card-text">{{message.bode_mail}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'sender:message_detail' message.pk %}" role="button">Подробно</a>
                </div>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}