blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import main_page, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(main_page), name='blog_main'),
    path('detail/<int:pk>', cache_page(60)(ArticleDetailView.as_view()), name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('sender/', include('email_sender.urls', namespace='sender')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    heading = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(blank=True, null=True, verbose_name='Содержимое статьи')
    image = models.ImageField(upload_to='blog/photo', blank=True, null=True)
    view_count = models.IntegerField(verbose_name='Количество просмотров', default=0)
    create_date = models.DateTimeField(verbose_name='дата публикации', blank=True, null=True)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return f'{self.heading} - {self.create_date}'

blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from blog.models import Article
from email_sender.models import Mailing, Client


# Create your views here.
def main_page(request):
    mailing_count = Mailing.objects.count()
    client_count = Client.objects.count()
    mailing_active_count = Mailing.objects.filter(status='start').count()
    article_rand = Article.objects.order_by('?')[:3]
    context = {'mailing_count': mailing_count,
               'client_count': client_count,
               'mailing_active_count': mailing_active_count,
               'article_rand_list': article_rand
               }
    return render(request, 'blog/main_page.html', context)

class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object

blog/templates/blog/article_detail.html
{% extends '../base.html' %}
{% block content %}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">Заголовок: {{object.heading}}</p>
              <p class="card-text">Текст статьи: {{object.content}}</p>
                <p class="card-text">Изображение: {{object.image}}</p>
                <p class="card-text">Дата публикации: {{object.create_date}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-primary" href="{% url 'blog:blog_main' %}" role="button">На главную</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/main_page.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form class="row" enctype="multipart/form-data">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <p>Общее количество рассылок: {{mailing_count}}</p>
                    <p>Общее число клиентов сервиса: {{client_count}}</p>
                    <p>Количество активных рассылок: {{mailing_active_count}}</p>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="container">
    <form class="row" enctype="multipart/form-data">
        {% for article in article_rand_list %}
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <p>Заголовок: {{article.heading}}</p>
                    <p>Контент: {{article.content}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'blog:blog_detail' article.pk %}" role="button">Подробно</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </form>
</div>
{% endblock %}